# Generated by Django 5.2.13 on 2026-04-16 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invitee_name', models.CharField(max_length=200)),
                ('invitee_timezone', models.CharField(max_length=64)),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('meeting_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('invitee_answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
