# Generated by Django 5.2.13 on 2026-04-16 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
            ],
            options={
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('color', models.CharField(default='#006BFF', max_length=7)),
                ('location_type', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('phone', 'Phone call'), ('in_person', 'In person'), ('custom', 'Custom')], default='google_meet', max_length=20)),
                ('buffer_before', models.PositiveSmallIntegerField(default=0)),
                ('buffer_after', models.PositiveSmallIntegerField(default=0)),
                ('custom_questions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_types',
            },
        ),
    ]
