# Generated by Django 5.2.13 on 2026-04-16 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='events.eventtype'),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['user', 'is_active'], name='event_types_user_id_86f1db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['user', 'event_type', 'day_of_week'], name='availabilit_user_id_adb3e5_idx'),
        ),
    ]
